/*
 * Jordan Stiver
 * 1.10.12
 * Homework1.java
 * First Homework assignment.
 */

package jordan;

import java.awt.Color;

import acm.graphics.GPen;
import acm.program.GraphicsProgram;

public class Homework1 extends GraphicsProgram
{

	public void run()
	{
		setSize(512, 386);
		while (true) {
			//Create and add GPen
			GPen pen = new GPen(197, 20);
			pen.showPen();
			add(pen);

			pen.setColor(Color.BLACK);
			pen.setSpeed(0.89);

			pen.drawLine(129, 0);
			pen.setLocation(197, 21);
			pen.drawLine(129, 0);
			pen.setLocation(197, 22);
			pen.drawLine(129, 0);
			pen.setLocation(197, 23);
			pen.drawLine(129, 0);
			pen.setLocation(197, 24);
			pen.drawLine(129, 0);
			pen.setLocation(197, 25);
			pen.drawLine(129, 0);
			pen.setLocation(197, 26);
			pen.drawLine(129, 0);
			pen.setLocation(197, 27);
			pen.drawLine(129, 0);
			pen.setLocation(197, 28);
			pen.drawLine(129, 0);
			pen.setLocation(197, 29);
			pen.drawLine(129, 0);
			pen.setLocation(197, 30);
			pen.drawLine(129, 0);
			pen.setLocation(197, 31);
			pen.drawLine(129, 0);
			pen.setLocation(197, 32);
			pen.drawLine(129, 0);
			pen.setLocation(197, 33);
			pen.drawLine(129, 0);
			pen.setLocation(197, 34);
			pen.drawLine(129, 0);
			pen.setLocation(197, 35);
			pen.drawLine(129, 0);
			pen.setLocation(197, 36);
			pen.drawLine(129, 0);
			pen.setLocation(197, 37);
			pen.drawLine(129, 0);
			pen.setLocation(197, 38);
			pen.drawLine(129, 0);
			pen.setLocation(197, 39);
			pen.drawLine(129, 0);
			pen.setLocation(197, 40);
			pen.drawLine(129, 0);

			pen.setLocation(197, 41);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(197, 42);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);

			pen.setLocation(153, 43);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 44);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 44);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 45);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 46);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 47);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 48);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 49);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 50);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 51);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 52);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 53);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 54);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 55);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 56);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 57);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 58);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 59);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);
			pen.setLocation(153, 60);
			pen.drawLine(65, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(20, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(65, 0);

			pen.setLocation(153, 61);
			pen.drawLine(20, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(20, 0);
			pen.setLocation(153, 62);
			pen.drawLine(20, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(20, 0);

			pen.setLocation(131, 63);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 63);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 64);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 65);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 66);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 67);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 68);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 69);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 70);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 71);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 72);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 73);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 74);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 75);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 76);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 77);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 78);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 79);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 80);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 81);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 82);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 83);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(131, 84);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(65, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);

			pen.setLocation(131, 85);
			pen.drawLine(21, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);

			pen.setLocation(111, 86);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 87);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 88);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 89);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 90);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 91);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 92);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 93);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 94);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 95);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 96);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 97);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 98);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 99);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 100);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 101);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 102);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 103);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(111, 104);
			pen.drawLine(41, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(89, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(44, 0);
			pen.setColor(Color.RED);
			pen.drawLine(21, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);

			pen.setLocation(111, 105);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 106);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 107);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 108);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 109);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 110);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 111);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 112);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 113);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 114);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 115);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 116);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 117);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 118);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 119);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 120);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 121);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 122);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 123);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 124);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 125);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 126);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 127);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 128);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 129);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);
			pen.setLocation(111, 130);
			pen.drawLine(16, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.RED);
			pen.drawLine(220, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(24, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(17, 0);

			pen.setLocation(89, 131);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 132);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 133);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 134);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 135);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 136);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 137);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 138);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 139);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 140);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 141);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 142);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 143);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 144);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 145);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 146);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 147);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 148);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);
			pen.setLocation(89, 149);
			pen.drawLine(38, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(38, 0);

			pen.setLocation(89, 150);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 151);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(84, 0);
			pen.setColor(Color.RED);
			pen.drawLine(46, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);

			pen.setLocation(89, 152);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 153);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 154);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 155);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 156);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 157);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 158);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 159);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 160);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 161);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 162);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 163);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 164);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 165);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 166);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 167);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 168);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 169);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 170);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 171);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 172);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 173);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 174);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 175);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 176);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 177);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 178);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 179);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 180);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 181);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 182);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 183);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 184);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 185);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 186);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 187);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 188);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 189);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 190);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 191);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 192);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 193);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(26, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(66, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);

			pen.setLocation(89, 194);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 195);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 196);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 197);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 198);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 199);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 200);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 201);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 202);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 203);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 204);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 205);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 206);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 207);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 208);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 209);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 210);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 211);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 212);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 213);
			pen.drawLine(18, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(124, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(45, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);

			pen.setLocation(89, 214);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 215);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 216);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 217);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 218);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 219);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 220);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 221);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 222);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 223);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 224);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 225);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 226);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 227);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 228);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 229);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 230);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 231);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 232);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 233);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 234);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 235);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 236);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 237);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89, 238);
			pen.drawLine(18, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(86, 0);
			pen.setColor(Color.RED);
			pen.drawLine(111, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);

			pen.setLocation(89,239);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,240);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,241);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,242);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,243);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,244);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,245);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,246);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,247);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,248);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,249);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,250);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,251);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,252);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,253);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,254);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,255);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,256);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,257);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,258);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);
			pen.setLocation(89,259);
			pen.drawLine(18,0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(214, 0);
			pen.setColor(Color.RED);
			pen.drawLine(47, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(18, 0);

			pen.setLocation(89, 260);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 261);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 262);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 263);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 264);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 265);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 266);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 267);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 268);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 269);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 270);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 271);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 272);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 273);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 274);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 275);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 276);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 277);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 278);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 279);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);
			pen.setLocation(89, 280);
			pen.drawLine(82, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(48, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(82, 0);

			pen.setLocation(109, 280);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 281);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 282);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 283);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 284);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 285);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 286);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 287);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 288);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 289);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 290);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 291);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 292);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 293);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 294);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 295);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 296);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 297);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 298);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 299);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 300);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 301);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);
			pen.setLocation(109, 302);
			pen.drawLine(42, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(46, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(19, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(68, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(42, 0);

			pen.setLocation(130, 303);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 304);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 305);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 306);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 307);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 308);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 309);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 310);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 311);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 312);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 313);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 314);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 315);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 316);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 317);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 318);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 319);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 320);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 321);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 322);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 323);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);
			pen.setLocation(130, 324);
			pen.drawLine(21, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(220, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(21, 0);

			pen.setLocation(130, 325);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 326);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 327);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 328);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 329);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 330);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 331);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 332);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 333);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 334);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 335);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 336);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 337);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 338);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 339);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 340);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 341);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 342);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 343);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 344);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 345);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 346);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);
			pen.setLocation(130, 347);
			pen.drawLine(41, 0);
			pen.setColor(Color.WHITE);
			pen.drawLine(180, 0);
			pen.setColor(Color.BLACK);
			pen.drawLine(41, 0);

			pen.setLocation(152, 348);
			pen.drawLine(217, 0);
			pen.setLocation(152, 349);
			pen.drawLine(217, 0);
			pen.setLocation(152, 350);
			pen.drawLine(217, 0);
			pen.setLocation(152, 351);
			pen.drawLine(217, 0);
			pen.setLocation(152, 352);
			pen.drawLine(217, 0);
			pen.setLocation(152, 353);
			pen.drawLine(217, 0);
			pen.setLocation(152, 354);
			pen.drawLine(217, 0);
			pen.setLocation(152, 355);
			pen.drawLine(217, 0);
			pen.setLocation(152, 356);
			pen.drawLine(217, 0);
			pen.setLocation(152, 357);
			pen.drawLine(217, 0);
			pen.setLocation(152, 358);
			pen.drawLine(217, 0);
			pen.setLocation(152, 359);
			pen.drawLine(217, 0);
			pen.setLocation(152, 360);
			pen.drawLine(217, 0);
			pen.setLocation(152, 361);
			pen.drawLine(217, 0);
			pen.setLocation(152, 362);
			pen.drawLine(217, 0);
			pen.setLocation(152, 363);
			pen.drawLine(217, 0);
			pen.setLocation(152, 364);
			pen.drawLine(217, 0);
			pen.setLocation(152, 365);
			pen.drawLine(217, 0);
			pen.setLocation(152, 366);
			pen.drawLine(217, 0);
			pen.setLocation(152, 367);
			pen.drawLine(217, 0);
			pen.setLocation(152, 368);
			pen.drawLine(217, 0);

			pen.hidePen();

			pause(2000);
			removeAll();
		}
	}
}
